export const products = [
    {
      id: "1",
      name: "Çimento",
      description: "Yüksek kaliteli portland çimento.",
      price: 75,
      brand: "ABC İnşaat",
      category: "Çimento",
      inStock: true,
      image: "https://example.com/cimento.jpg",
      reviews: [],
    },
    {
      id: "2",
      name: "Pirket",
      description: "Dayanıklı beton pirket.",
      price: 2.5,
      brand: "Beton Yapı",
      category: "Beton",
      inStock: true,
      image: "https://example.com/pirket.jpg",
      reviews: [],
    },
    {
      id: "3",
      name: "Demir 12mm",
      description: "Yüksek mukavemetli inşaat demiri.",
      price: 50,
      brand: "DemirSA",
      category: "Demir",
      inStock: true,
      image: "https://example.com/demir12mm.jpg",
      reviews: [],
    },
    {
      id: "4",
      name: "Tuğla",
      description: "Yüksek dayanımlı kil tuğla.",
      price: 1.2,
      brand: "Tuğla Yapı",
      category: "Tuğla",
      inStock: true,
      image: "https://example.com/tugla.jpg",
      reviews: [],
    },
    {
      id: "5",
      name: "Kum",
      description: "İnşaat için elenmiş kum.",
      price: 15,
      brand: "Kumcu",
      category: "Kum",
      inStock: true,
      image: "https://example.com/kum.jpg",
      reviews: [],
    },
    {
      id: "6",
      name: "Alçı",
      description: "Yüksek kaliteli duvar alçısı.",
      price: 25,
      brand: "Alçıpan",
      category: "Alçı",
      inStock: true,
      image: "https://example.com/alci.jpg",
      reviews: [],
    },
    {
      id: "7",
      name: "Seramik Fayans",
      description: "Banyo ve mutfak için seramik fayans.",
      price: 50,
      brand: "Seramik Zemin",
      category: "Seramik",
      inStock: true,
      image: "https://example.com/seramik.jpg",
      reviews: [],
    },
    {
      id: "8",
      name: "Beton",
      description: "Hazır dökme beton.",
      price: 350,
      brand: "Beton İnşaat",
      category: "Beton",
      inStock: true,
      image: "https://example.com/beton.jpg",
      reviews: [],
    },
    {
      id: "9",
      name: "Kiremit",
      description: "Dayanıklı kil kiremit.",
      price: 1.5,
      brand: "Çatı Malzemeleri",
      category: "Kiremit",
      inStock: true,
      image: "https://example.com/kiremit.jpg",
      reviews: [],
    },
    {
      id: "10",
      name: "Taş Yünü Yalıtım",
      description: "Isı ve ses yalıtımı için taş yünü.",
      price: 150,
      brand: "Yalıtım Market",
      category: "Yalıtım",
      inStock: true,
      image: "https://example.com/tasyunu.jpg",
      reviews: [],
    },
    // ... 40 tane daha ürün ekleyin.
  ];
  